version: '3.4'
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

  backend:
    build:
      context: ./src/ConsultaFilmes/ConsultaFilmes.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    environment:
      - CYPRESS_baseUrl=http://localhost
    volumes:
      - ./cypress:/e2e
      - ./cypress.config.js:/cypress.config.js
    command: npx cypress run